### PR TITLE
allow chinese characters and compiling to work even on non-chinese  s…

### PR DESCRIPTION
**Pull request by WalterCouto**
…ystems

### CODE REVIEW

**Comment by daidodo** [comment]
@WalterCouto, thanks for the PR!

* Could you add more details of the issue you are trying to solve in the PR?
* I can see there are many noises in the commits. Could you remove them so I can focus on the real changes?

**Comment by WalterCouto** [comment]
- being on a non-Chinese OS, the C++ file being encoded in Chinese instead of UTF-8 causes issues.  this converts all files to UTF-8 with BOM which visual supports.  This allows any code page to see the characters properly. Some of what looks like nose is just the fact the encoding changed for the file and it's required for the characters not to look corrupted on non-Chinese code pages.
- The language.txt with the UI text was changed to UTF 8 NO BOM, (this is why in a previous PR the text looks like it was corrupted in the diff when if fact is looked good locally). you can see now in the diff that the Chinese characters shows up properly now.
- The RC files must be in UTF-16LE for any characters outside the codepage to compile properly on  a non-Chinese codepage
- Lastly a switch to VS 2019 and C++17 compiling just to bring up to a more modern compiler.

With these changes, I can contribute and compile no matter what codepage my machine is on and not affect others in other codepages.

**Comment by daidodo** [comment]
Really appreciate your work!

I tested locally and found *CharacterDialogBase.h* is not properly encoded (UTF8 without BOM).
After fixing, it did fix encoding problem in non-Chinese env.

But there is one issue:
I intended to use VS2017 because it supports WinXP executables and I need it for my local bnet. Could you revert that? (Or if you find a way to support WinXP then I'm OK).

Thanks!

**Comment by WalterCouto** [comment]
I'll rework it to use winxp and 2017. I think 2019 may still support it, I'll make the changes and let you know.

**Comment by WalterCouto** [comment]
@daidodo I added back the XP compiling as it was in the original project file. As well as check all .h and .cpp files again to make sure they had proper encoding.  Let me know if there are any other issues.

**Comment by daidodo** [comment]
Thanks for the update!

Just one issue that the Property window becomes narrow in Chinese.

image

Could you fix it?
I'll merge the PR but not publish a release until it's fixed.

**Pull request merged**
